spring.application.name=LMS
server.port=8080

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/lms_portofolio
spring.datasource.username=postgres
spring.datasource.password=Admin123456
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false


# Flyway
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration

# Debugging - lihat nilai parameter yang di-bind ke query SQL
logging.level.org.hibernate.orm.jdbc.bind=TRACE